# Generated by Django 3.2 on 2021-05-17 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sekolah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('kepsek', models.CharField(max_length=200)),
                ('lokasi', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Murid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('umur', models.PositiveIntegerField()),
                ('sekolah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siswa', to='basic_app.sekolah')),
            ],
        ),
    ]
